name: Nightly-Build

on:
  workflow_dispatch:
  push:
    branches: [ nightly-build ]
  pull_request:
    branches: [ nightly-build ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish "MSFSTouchPortalPlugin" --output ".\out\dist" --configuration Release -p:Platform=x64 $VersionSuffixCommand $VersionSuffix -r "win-x64" --self-contained true
      run: dotnet run -p "MSFSTouchPortalPlugin-Generator" ".\out"
      run: cp README.md ".\out"
      run: cp CHANGELOG.md ".\out"
      run: cp airplane_takeoff24.png ".\out"
    - name: Create TPP
      uses: papeloto/action-zip@v1
      with:
        files: dist/
        recursive: true
        dest: Test.tpp
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.14
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Release.txt

